### ISSUE TITLE
Tutor 18 compatibility ?

### ISSUE THREAD

**Issue by RonanFR** [aulasneo/tutor-contrib-translations#1]
Is this plugin still relevant with the last tutor release (18) ?

From what I understood in the [changelog](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md) the translations are now pulled via atlas.

**Comment by angonz** [comment]
Hi @RonanFR!
Probably not, that's why I didn't push any 18 tag. I haven't checked atlas or how can we create custom translations, but if it is satisfactory then probably there will be no need for this plugin in the future.
